(require 'company-lsp)
(push 'company-lsp company-backends)
(require 'lsp-clangd)
(when (equal system-type 'darwin)
  (setq lsp-clangd-executable "/usr/local/opt/llvm/bin/clangd"))
(add-hook 'c++-mode-hook #'lsp-clangd-c++-enable)
