(require 'rust-mode)
(setq rust-indent-offset 2)
(setq rust-format-on-save t)
(add-hook 'rust-mode-hook #'racer-mode)
(add-hook 'rust-mode-hook #'cargo-minor-mode)
(add-hook 'rust-mode-hook #'prettify-symbols)
(add-hook 'racer-mode-hook #'eldoc-mode)
(add-hook 'racer-mode-hook #'company-mode)
(define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
(setq company-tooltip-align-annotations t)
(add-hook 'flycheck-mode-hook #'flycheck-rust-setup)

(defun prettify-symbols ()
  (setq-local
   prettify-symbols-alist
   (append
    '(("->" . ?→)
      ("=>" . ?⇒)
      (">=" . ?≥)
      ("<=" . ?≤)
      ("!=" . ?≠)
      ("==" . ?≡)
      (".." . ?‥)
      ("...". ?…)
      ("fn" . ?ƒ)
      ("Fn" . ?𝘍))
    prettify-symbols-alist)))
